# Site wide configuration

title: jfx.commons
locale: en_US
description: Some useful JavaFX stuff.
logo: site-logo.png
search: true
url: http://dejv78.github.io/jfx.commons/

# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..2
  use_coderay: false

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md", "vendor"]


# Site owner
owner:
  name: dejv
  avatar: bio-photo.jpg
  email: dejv78@gmail.com
  twitter: dejv78cz
  github: dejv78

